# Generated by Django 3.1.7 on 2021-03-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='register_passphrase',
            field=models.TextField(),
        ),
    ]
