# Generated by Django 3.1.7 on 2021-03-08 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20210307_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwords',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='passwords',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
