# Generated by Django 3.1.7 on 2021-03-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20210308_0557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwords',
            options={'ordering': ('registered_email_address',)},
        ),
        migrations.RemoveField(
            model_name='passwords',
            name='color',
        ),
        migrations.AddField(
            model_name='passwords',
            name='qrcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode'),
        ),
    ]
