# Generated by Django 3.1.7 on 2021-03-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20210314_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwords',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
